steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/$PROJECT_ID/eso-app:$COMMIT_SHA
    - --cache=true
    - --cache-ttl=168h
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'eso-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/eso-app:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
images:
    - 'gcr.io/$PROJECT_ID/eso-app:$COMMIT_SHA'