steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/$PROJECT_ID/eso-app:latest
    - --cache=true
    - --cache-ttl=168h
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
     - 'run'
     - 'deploy'
     - 'eso-app'
     - '--image'
     - 'gcr.io/$PROJECT_ID/eso-app:latest'
     - '--region'
     - 'us-central1'
     - '--memory'
     - '4G'
images:
  - 'gcr.io/$PROJECT_ID/eso-app:latest'