[project]
name = "eso-website"
version = "0.1.2"
description = ""
authors = [{ name = "Stéphane Thibaud", email = "snthibaud@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "streamlit",
    "esovalue>=0.1.15",
    "pandas",
    "numpy",
]

[tool.uv]
package = false

[tool.uv.sources]
esovalue = { path = "../../../ESOValue", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
